### PR TITLE
Pie chart

### PR DESCRIPTION
**Pull request by Benny121221**
New contributors should review CONTRIBUTING.md:
https://github.com/swharden/ScottPlot/blob/master/CONTRIBUTING.md

**Purpose:**
Adds a pie chart plottable.

**New functionality (code):**
Provide a code example demonstrating new functionality achieved with this pull request (if applicable)

```cs
double[] proportions = new double[5];
double total = 0;
for (int i = 0; i < proportions.Length; i++)
{
	if (total >= 1) {
		break;
	}
	proportions[i] = rand.NextDouble() * (1 - total);   //Make sure we don't add up to more than 1
	total += proportions[i];
}
if (total < 1) {
	proportions[proportions.Length - 1] += 1 - total; //If we are less than 1, add the remnant to the last slice
}

plt.PlotPie(proportions);
plt.Legend();
```

**New functionality (image):**
image

### CODE REVIEW

**Comment by Benny121221** [comment]
Not to point the finger, but that build failed because of a file I had no clue existed, so I'm pretty sure it's not because of this PR

**Comment by swharden** [comment]
> Not to point the finger, but that build failed because of a file I had no clue existed, so I'm pretty sure it's not because of this PR

Ha, that was me. I added a new project to the main solution tonight and I guess a path got messed up.  I think it's fixed now so if you merge maser into this branch it should build properly.

This is excellent progress! What do you think about an "exploded" pie chart? gaps between the slices? And also labels and/or values somewhere on the plot? I'm thinking the demo would look best if the grid and axes were disabled too

```cs
plt.Grid(false);
plt.Frame(false);
plt.Ticks(false, false);
```

**Comment by Benny121221** [comment]
I rebased, lets see if it works.

And I can have a look at those suggestions.

**Comment by swharden** [comment]
> I rebased, lets see if it works.

Success!

> And I can have a look at those suggestions.

I recognize the "exploding" effect isn't trivial to implement... but it would look pretty cool, and I look forward to seeing what you come up with!

**Comment by Benny121221** [comment]
How's this for an exploding effect?

image

**Comment by swharden** [comment]
It's looking close! I'm a bit confused why/how some pie slice tips are touching each other while some others are not 🤔

**Comment by Benny121221** [comment]
Because they're small slices, the midpoint of their arc are in approximately the same spot. Which means when you explode the pie they move in the same direction.

Excel avoids this problem by adding an outline to the slices:
image

**Comment by swharden** [comment]
Heh, Excel takes the easy path 😝

I haven't looked it up yet so I don't know the answer, but what does matplotlib do? My go-to is usually to mimic their behavior.

**Comment by Benny121221** [comment]
I'm not sure about matplotlibs behaviour. How does this one look?

image

**Comment by Benny121221** [comment]
And I'm not sure we want to emulate matplotlib in this situation...
image

**Comment by Benny121221** [comment]
matplotlib does this:

image

It doesn't draw an outline around the whole thing, which means if one of the slices is large, their edges don't line up:

image

Otherwise, it seems to act the same as excel. I can turn off the outline, but I think it looks better

**Comment by swharden** [comment]
This is an excellent improvement to this libraries capabilities. Thanks @Benny121221!

**Pull request merged**
