### PR TITLE
BoxAndWhisker improvements

### PR DESCRIPTION
**Pull request by Benny121221**
… individual points

As before, here is the code that I used to test:

```
using ScottPlot;
using System;
using System.Diagnostics;

namespace ScottPlotTesting
{
	class Program
	{
		static void Main(string[] args)
		{
			Random rand = new Random();
			var plt = new ScottPlot.Plot(600, 400);
			string filename = "test.png";
			double[] xs = new double[3];
			double[][] ys = new double[3][];
			for (int i = 0; i < ys.Length; i++)
			{
				xs[i] = i;
				ys[i] = new double[10];
				for (int j = 0; j < 10; j++)
				{
					if (j == 0)
					{
						ys[i][j] = 2;//Just to guarantee that there is an outlier
						continue;
					}
					ys[i][j] = rand.NextDouble();
				}
			}

			ScottPlot.Statistics.BoxAndWhisker[] boxAndWhisker = new ScottPlot.Statistics.BoxAndWhisker[ys.Length];
			for (int i = 0; i < ys.Length; i++) {
				boxAndWhisker[i] = ScottPlot.Statistics.BoxAndWhiskerFromData.GetBoxAndWhisker_OutliersAndQuartiles(ys[i], i);
			}
			plt.PlotBoxAndWhisker(boxAndWhisker);

			plt.SaveFig(filename);

			using (Process proc = new Process())
			{ // This is to open the file automatically, if you're on linux, you need xdg-open
				proc.StartInfo.FileName = filename;
				proc.StartInfo.UseShellExecute = true;
				proc.Start();
			}
		}
	}
}

```

You can use `Statistics.BoxAndWhiskerFromData.GetBoxAndWhisker_OutliersAndQuartiles` or `Statistics.BoxAndWhiskerFromData.GetBoxAndWhisker_LimitsAndDeviation`, I tested both, they both work fine.

### CODE REVIEW

**Comment by Benny121221** [comment]
Made some small oversights in the first commit

**Comment by StendProg** [comment]
> //These could be made faster knowing that we have already sorted the list above

Possible small improvements assuming sorted array
```c#
lowOutliers = sortedValues.TakeWhile(y => y < lowerBoundary).ToArray();
...
minNonOutlier = sortedValues.Reverse().TakeWhile(y => y > lowerBoundary).LastOrDefault();
maxNonOutlier = sortedValues.TakeWhile(y => y < upperBoundary).LastOrDefault();
```

**Comment by Benny121221** [comment]
Did you one better, both the lists of outliers and the min/max non-outliers can be optimized knowing that the list is sorted

**Comment by StendProg** [comment]
Yep that's most performance. But you don't need temponary lists. You can find indexes and then use `Array.Copy` from SortedArray to results with right indexing.
Anyway this improvements cost nothing, because main time consumption is initial sort.
In this case previous linq also have rights to exist. (easy to read).

**Comment by Benny121221** [comment]
You got it chief

**Comment by swharden** [comment]
@Benny121221 thanks for this one too! It looks great!

I might continue to refine it a bit over the next few days. I'll track further work on this in #251

**Pull request merged**
