### PR TITLE
Avalonia

### PR DESCRIPTION
**Pull request by Benny121221**
New contributors should review [CONTRIBUTING.md](https://github.com/swharden/ScottPlot/blob/master/CONTRIBUTING.md)

**Purpose:**
Adds Avalonia UserControl.
#496 

**New functionality (code):**
Provide a code example demonstrating new functionality achieved with this pull request (if applicable):

It seems inappropriate to drop several files in here, but I have a repo which I used for testing: https://github.com/Benny121221/ScottPlotTesting/tree/master/src/AvaloniaTesting

You'll notice that Avalonia feels very similar to WPF. Note that you'll have to point to a built ScottPlot dll, otherwise it won't find the assembly.

**New functionality (image):**
If this pull request changes how a plot is rendered, provide an image or screenshot demonstrating the new functionality:
image

**Autoformat your code:**
The build will fail if your code is not auto-formatted. Auto-format your code in Visual Studio, or from the console using these commands:
```
cd ScottPlot/src/
dotnet tool install --global dotnet-format
dotnet format
```

### CODE REVIEW

**Comment by Benny121221** [comment]
Looks like I need to rebase :/

**Comment by Benny121221** [comment]
Ah, you made some changes in 2a8c3cfd242b05f7de20f2f19aa378a70642d69e that complicated things, that's all

**Comment by Benny121221** [comment]
I don't think that's my fault because I ran `dotnet-format` locally and it made no changes

**Comment by swharden** [comment]
It's looking good! 

I haven't looked into it too deeply yet, but why doesn't the control resize when the window does? 🤔 

image

**Comment by Benny121221** [comment]
Avalonia does not have a resize event. I noticed this at the time and realized the workaround could be annoying so I decided to leave it for later. I then forgot about it -_-

If you're interested, this is the relevant portion: https://github.com/swharden/ScottPlot/blob/cd6c59a6f0d4b502ba9a7c028730d386c348231e/src/ScottPlot.Avalonia/AvaPlot.axaml.cs#L82:L94

**Pull request merged**
