### PR TITLE
Fixes linreg slope issue and gets rid of xspacing thing

### PR DESCRIPTION
**Pull request by Benny121221**
#290

### CODE REVIEW

**Comment by Benny121221** [comment]
This does have **one** breaking change, the signature of `GetResiduals` was changed because there is no reason for it to take a parameter

**Comment by Benny121221** [comment]
Even though the xspacing thing is  no longer used in the code, you can still use that constructor

**Comment by StendProg** [comment]
Hi @Benny121221.
I checked your PR.
Can you calculate `xs.Average()` `ys.Average()` only once, and then use this calculated values.
```c#
meanX = xs.Average();
meanY = ys.Average();
...
sumXYResidual += (xs[i] - meanX) * (ys[i] - meanY);
sumXSquareResidual += (xs[i] - meanX) * (xs[i] - meanX);
...
```

**Comment by Benny121221** [comment]
I got you bud

**Comment by swharden** [comment]
Thanks @Benny121221 this looks great! There's a bit more work to do (#290) but this is an excellent improvement.

**Pull request merged**
