### PR TITLE
Donut pie chart

### PR DESCRIPTION
**Pull request by Benny121221**
New contributors should review [CONTRIBUTING.md](https://github.com/swharden/ScottPlot/blob/master/CONTRIBUTING.md)

**Purpose:**
#533

**New functionality (code):**
Provide a code example demonstrating new functionality achieved with this pull request (if applicable):

```cs
plt.PlotPie(values, donut: true);
```

**New functionality (image):**
If this pull request changes how a plot is rendered, provide an image or screenshot demonstrating the new functionality:
image
Note this screenshot uses both an exploded and a donutted pie chart.

**Autoformat your code:**
The build will fail if your code is not auto-formatted. Auto-format your code in Visual Studio, or from the console using these commands:
```
cd ScottPlot/src/
dotnet tool install --global dotnet-format
dotnet format
```

### CODE REVIEW

**Comment by Benny121221** [comment]
I did it with clipping, not an opaque blob. This means that you can have things poking out from under it.

**Comment by AlexFsmn** [comment]
Looks good!

2 questions:
1. Is it possible to choose the thickness?
2. Would it be easy to add a similar plot where you only have one value in %?
Similar to this:
Chart

**Comment by Benny121221** [comment]
Custom Donut Size (size of 0.9 for demonstration purposes):

image

**Comment by Benny121221** [comment]
With percentage in the middle:

image

**Comment by AlexFsmn** [comment]
Great job!
Maybe the single value plot should be a separate class though since you only need to specify a value between 0-100?
@swharden, what do you think?

**Comment by swharden** [comment]
This came together nicely! I exposed some properties to make it easier to customize (without modifying the original Plot module that was there before). I think I'm going to try to slowly move in this direction, probably marking the old constructors obsolete in ScottPlot 4.1

It was a bit of a surprise that clipping masks aren't anti-aliased... I know I suggested using them, but it's hard not to feel a little let down that an anti-aliased donut has an aliased hole! It's fine how it is, but I thought I'd mention it.

Thanks for all your work on this @Benny121221!

Regarding @AlexFsmn's original suggestion:
image

I don't think it makes sense for an image like this to have a "coordinate system", so it probably shouldn't be a "plot" in the first place. An image like this could be created with just a few lines of C# using System.Drawing to draw some circles (totally eliminating the massive complexities that come with plotting a mouse-interactive coordinate system)... so extensive support for these types of panels probably won't be a priority of ScottPlot development moving forward. That said, we got a pretty cool effect here and I'm happy where this ended up!

**Pull request merged**
