### PR TITLE
Add PlottableDragEventArgs

### PR DESCRIPTION
**Pull request by charlescao460**
**New Contributors:**
please review [CONTRIBUTING.md](https://github.com/swharden/ScottPlot/blob/master/CONTRIBUTING.md)

**Purpose:**
As mentioned in #592 , added events and handler when draggables are dragged.

**New Functionality:**
Added PlottableDragEventArgs in `ScottPlot` namespace
Such event was raised in `WpfPlot` and `FormsPlot`, but not implemented in Avalonia.

Tested in WPF: See demo codes here: https://github.com/charlescao460/ScottPlot/tree/DragEvent-Demo/src/ScottPlot.Demo.WPF.DraggableEvent
```cs
_hSpan = Plot.plt.PlotHSpan(0, 0.1, Color.Crimson, draggable: true, dragFixedSize: true);
Plot.MouseDragPlottable += OnMouseDrag;

...

private void OnMouseDrag(object sender, PlottableDragEventArgs agrs)
{
   if (agrs.Draggable == _hSpan)
   {
      TextBox.Text += "\nDrag H-Span!";
   }
}
```

image

**Note:**

Not sure if I need to change WinForm's event handler to `PlottableDragEventHandler`, because it will break backward compatibility. 

And in WPF, the mouse up event is named `OnMouseUpPlottable` rather than  `OnMouseDropPlottable`, which makes more sense to me.

This feature is not implemented in Avalonia. And I didn't find automated UI test so I didn't add test.

### CODE REVIEW

**Comment by charlescao460** [comment]
src/ScottPlot.Demo.WPF/AssemblyInfo.cs
And
src/ScottPlot.WPF/AssemblyInfo.cs 
Are formatted by autoformat.bat

**Comment by StendProg** [comment]
Hi @charlescao460, it looks fine.

There is some questions:
1. Does `plot` field in `PlottableDragEventArgs` realy needed? You can easy find it in event `source`, `source->plt`.
2. Does `EventType` field in `PlottableDragEventArgs` really needed? You already have different types of events which indicate event type.

There is probably nothing wrong with duplication, it can be convenient in some scenarios.

**Comment by charlescao460** [comment]
Hi @StendProg 

Good point! I've changed my codes according to your suggestion. They look nicer now.

**Comment by swharden** [comment]
Thanks @charlescao460 and @StendProg! Sorry I've taken a while to get to this (I've been pretty busy with #578).

I agree with @StendProg it's a good idea to isolate GUI code (events and mouse/keyboard interactions) to the GUI packages, and I can see that is what was done here with support for both WinForms and WPF. Thanks again!

**Pull request merged**
