### PR TITLE
Added support to draw signal plots using gradient fill.

### PR DESCRIPTION
**Pull request by AlexFsmn**
**Purpose:**
Added support to draw signal plots using gradient as well as solid fill.

**New functionality (code):**
```cs
double[] data = new double[] { 51, -5, 6, 12, 3 };
var plt = new ScottPlot.Plot(400, 300);
plt.PlotSignal(data, minRenderIndex: 1, maxRenderIndex: 4, fill: true, fillColor1: Color.Blue, fillColor2: Color.Transparent);
```

**New functionality (image):**
GradientPlottableSignal

### CODE REVIEW

**Comment by swharden** [comment]
Hi @AlexFsmn, thanks for this PR! The aesthetic is fantastic!

### Determining the Edge

It might be nice to have the shaded area extend to the bottom of the view area, rather than the minimum value of the signal itself. The current method produces an unexpected interactive experience:
fill


The easiest way to do this is is probably to replace those lines:
https://github.com/swharden/ScottPlot/blob/88319299a1ef9ce9f4289fafdf1e59b8bfce1a40/src/ScottPlot/plottables/PlottableSignalBase.cs#L285-L286

With something like:

```cs
float minVal = 0;
float maxVal = settings.dataSize.Height;
```

I made the change and committed to this PR. What do you think?

This always looks nice as a single image, but interactively the effect is slightly unexpected. I think this is a step in the right direction though...

fill2

### Supporting FillAbove and FillBelow

Similarly, I'm curious if the `bool fill` argument should change to some type of `enum` like `NoFill, FillBelow, GradientBelow, FillAbove, GradientAbove`. Supporting "fill above" probably just involves tweaking the two lines of code cited above too 🤔 

### Supporting FillAboveAndBelow

How much work do you think it would take to achieve an effect like this? This was previously requested (#255) and I made it work with Scatter plots, but I can see this being requested around the corner if we add shaded support to signal plots.

image

Note that in this example the "split" between the colors is 0, but it would be fantastic if the user could define that too.

### Let's keep the constructor simple

We're experimenting with additional styling options options for edge cases. I recognize the existing style is to have methods with long lists of optional arguments and plottables with huge constructors, however I'm trying to move away from this in favor of plottables with exposed public properties the user can tweak to achieve advanced styling functionality. 

As you found, those huge constructors are a pain to update as you add little styling tweaks, so I'm hoping this will be an easier format to maintain moving forward. I modified this PR to use this newer style, and updated the cookbook demos accordingly. This PR is much simpler now, with only 2 modified files 👍 

I look forward to hearing your thoughts on the above! Thanks again for all your work here, this is looking _really_ nice!

**Comment by AlexFsmn** [comment]
Yes, I think the change on how the edge is handled is better now.
Another way of handling this is would be to set the global minimum instead of the local minimum. However, this might affect performance(?).
About fill above & fill above & below: I made a few changes that should take care of this.
You can have a look at this and tell me what you think:
GradientPlottableSignalAboveAndBelow

I also added a fill type as you suggested. Seems like the better choice if multiple types should be supported :)
..Also tell me if the location of the enum should be in another place.

**Comment by AlexFsmn** [comment]
Ah.. Seems like I didn't zoom in enough when testing.
I think this is a good start but has a few problems. Gradient colors doesn't seem to work as good as I though. There is also a problem with the color rendering around the baseline. Will look into this later.

**Comment by swharden** [comment]
> Another way of handling this is would be to set the global minimum instead of the local minimum. However, this might affect performance(?)

I think if the min/max calculation is performed on `linePoints` (rather than `ys`) it will be very fast. I like this idea!

> You can have a look at this and tell me what you think

> Also tell me if the location of the enum should be in another place

I think this is looking wonderful! Thanks again for working toward this excellent improvement.

> I think this is a good start but has a few problems. Gradient colors doesn't seem to work as good as I though. There is also a problem with the color rendering around the baseline. Will look into this later.

Graphics programming can be finicky sometimes! I'll let you work toward putting the finishing touches on this, and I'll take a closer look and merge it in when you think it's ready 👍

**Comment by AlexFsmn** [comment]
> I think if the min/max calculation is performed on linePoints (rather than ys) it will be very fast. I like this idea!

Ok! Might change to this later on.
I changed the new rendering "above and below" to work as the other types for now.
A also fixed the rendering issue around the baseline. 😀
Have a look and let me know what you think. The gradient example creates a kind of "focus" effect if you choose transparent as your second color. Looks kinda cool even though this wasn't the plan.

**Comment by AlexFsmn** [comment]
Add some styling and it looks pretty good!
DarkGradientPlottableSignalAboveAndBelow

**Pull request merged**
