### PR TITLE
Delayed HQ render after mousewheel event

### PR DESCRIPTION
**Pull request by StendProg**
Additional speed improvement to PR #89.
Allow zoom with mouse wheel at high speed.
Mouse Wheel event render whith AA off, after configurable delay it render with current setting.
This PR will make legend looks bad on mouse wheel scroll too. #92

### CODE REVIEW

**Comment by swharden** [comment]
I like this behavior. 

What do you think about doing the same thing on the MouseUp events? Click-dragging would be low quality, and it would wait a bit after releasing the mouse before rendering in high quality?

Perhaps this would it make it more obvious to the user it's rendering in low quality (and not just appear glitchy)

**Comment by StendProg** [comment]
I can make it, but not today. And i prefer keep old PR #89 behavior as a configurable option. Delayed render for mouse wheel this is a necessary action, but not for mouse up that can RenderHQ  instantly.

**Comment by StendProg** [comment]
HQ render after delay on mouse up. Delay can be set with mouseUpHQRenderDelay = 300.
 With using mouseUpHQRenderDelay = 0 it works like in PR #89.

**Comment by swharden** [comment]
This works great, thanks @StendProg!

**Pull request merged**
